import { PrismaClient, SubscriptionTierType, Gender, Prisma } from '@prisma/client';
const prisma = new PrismaClient();

type VoiceSeed = Omit<Prisma.VoiceCreateInput, 'created_at' | 'updated_at'> & { sortOrder?: number };

const voices: VoiceSeed[] = [
  {
    voice_id: "onwK4e9ZLuTAKqWW03F9",
    name: "Daniel", // good
    speed: 0.8,
    tier: SubscriptionTierType.free,
    price_multiplier: 1.0,
    languages: ["en", "es", "fr", "de", "zh", "ja", "ko", "pt", "hi", "ru"],
    gender: Gender.male,
    labels: ["Authoritative", "Middle-Aged"],
    accent: "British",
  },
  {
    voice_id: "p43fx6U8afP2xoq1Ai9f",
    name: "Emily", //good
    speed: 0.8,
    tier: SubscriptionTierType.free,
    price_multiplier: 2.0,
    languages: ["en", "es", "fr", "de", "zh", "ja", "ko", "pt", "hi", "ru"],
    gender: Gender.female,
    labels: ["Relaxed", "Middle-Aged"],
    accent: "Australian",
  },
  {
    voice_id: "Atp5cNFg1Wj5gyKD7HWV",
    name: "Christina",
    speed: 1.0,
    tier: SubscriptionTierType.starter,
    price_multiplier: 2.0,
    languages: ["en", "es", "fr", "de", "zh", "ja", "ko", "pt", "hi", "ru"],
    gender: Gender.female,
    labels: ["Whispery", "Middle-Aged"],
  },
  {
    voice_id: "pjcYQlDFKMbcOUp6F5GD",
    name: "Elena", // good
    speed: 0.8,
    tier: SubscriptionTierType.free,
    price_multiplier: 1.0,
    languages: ["en", "es", "fr", "de", "zh", "ja", "ko", "pt", "hi", "ru"],
    gender: Gender.female,
    labels: ["Calm", "Young"],
    accent: "American",
  },
  {
    voice_id: "flq6f7yk4E4fJM5XTYuZ", //good
    name: "Michael",
    speed: 0.8,
    tier: SubscriptionTierType.starter,
    price_multiplier: 1.0,
    languages: ["en", "es", "fr", "de", "zh", "ja", "ko", "pt", "hi", "ru"],
    gender: Gender.male,
    labels: ["Calm", "Old"],
    accent: "American",
  },
  {
    voice_id: "PB6BdkFkZLbI39GHdnbQ",
    name: "Natasha",
    speed: 1.0,
    tier: SubscriptionTierType.pro,
    price_multiplier: 2.0,
    languages: ["en", "es", "fr", "de", "zh", "ja", "ko", "pt", "hi", "ru"],
    gender: Gender.female,
    labels: ["Sensual", "Middle-Aged"],
  },
  {
    voice_id: "XrExE9yKIg1WjnnlVkGX", //good
    name: "Matilda",
    speed: 0.7,
    tier: SubscriptionTierType.starter,
    price_multiplier: 1.0,
    languages: ["en", "es", "fr", "de", "zh", "ja", "ko", "pt", "hi", "ru"],
    gender: Gender.female,
    labels: ["Friendly", "Middle-Aged"],
    accent: "American",
  },
  {
    voice_id: "IKne3meq5aSn9XLyUdCD", //good
    name: "Charlie",
    speed: 0.8,
    tier: SubscriptionTierType.free,
    price_multiplier: 1.0,
    languages: ["en", "es", "fr", "de", "zh", "ja", "ko", "pt", "hi", "ru"],
    gender: Gender.male,
    labels: ["Middle-Aged", "Calm"],
    accent: "Australian",
  },
  {
    voice_id: "BL7YSL1bAkmW8U0JnU8o", //good
    name: "Angelina",
    speed: 0.9,
    tier: SubscriptionTierType.starter,
    price_multiplier: 1.0,
    languages: ["en", "es", "fr", "de", "zh", "ja", "ko", "pt", "hi", "ru"],
    gender: Gender.female,
    labels: ["Calm", "Middle-Aged"],
  },
  {
    voice_id: "iiidtqDt9FBdT1vfBluA", //good
    name: "Clint",
    speed: 0.8,
    tier: SubscriptionTierType.starter,
    price_multiplier: 1.0,
    languages: ["en", "es", "fr", "de", "zh", "ja", "ko", "pt", "hi", "ru"],
    gender: Gender.male,
    labels: ["Old", "Rugged", "Warm"],
  },
  
  // Remaining language-agnostic voices
  {
    voice_id: "XB0fDUnXU5powFXDhCwa",
    name: "Charlotte",
    speed: 0.9,
    tier: SubscriptionTierType.free,
    price_multiplier: 1.0,
    languages: ["en", "es", "fr", "de", "zh", "ja", "ko", "pt", "hi", "ru"],
    gender: Gender.female,
    labels: ["Seductive", "Young"],
  },
  {
    voice_id: "nPczCjzI2devNBz1zQrb",
    name: "Brian",
    speed: 0.8,
    tier: SubscriptionTierType.starter,
    price_multiplier: 1.0,
    languages: ["en", "es", "fr", "de", "zh", "ja", "ko", "pt", "hi", "ru"],
    gender: Gender.male,
    labels: ["Deep", "Middle-Aged"],
    accent: "American",
  },
  {
    voice_id: "GBv7mTt0atIp3Br8iCZE",
    name: "Thomas",
    speed: 0.8,
    tier: SubscriptionTierType.starter,
    price_multiplier: 1.0,
    languages: ["en", "es", "fr", "de", "zh", "ja", "ko", "pt", "hi", "ru"],
    gender: Gender.male,
    labels: ["Calm", "Young"],
    accent: "American",
  },
  {
    voice_id: "pqHfZKP75CvOlQylNhV4",
    name: "Bill",
    speed: 0.8,
    tier: SubscriptionTierType.starter,
    price_multiplier: 1.0,
    languages: ["en", "es", "fr", "de", "zh", "ja", "ko", "pt", "hi", "ru"],
    gender: Gender.male,
    labels: ["Old", "Trustworthy"],
    accent: "American",
  },
  {
    voice_id: "piTKgcLEGmPE4e6mEKli",
    name: "Nicole",
    speed: 0.8,
    tier: SubscriptionTierType.pro,
    price_multiplier: 1.0,
    languages: ["en", "es", "fr", "de", "zh", "ja", "ko", "pt", "hi", "ru"],
    gender: Gender.female,
    labels: ["ASMR", "Soft", "Young"],
    accent: "American",
  },
  {
    voice_id: "pFZP5JQG7iQjIQuC4Bku", //Lily
    name: "Helen",
    speed: 0.75,
    tier: SubscriptionTierType.free,
    price_multiplier: 1.0,
    languages: ["en", "es", "fr", "de", "zh", "ja", "ko", "pt", "hi", "ru"],
    gender: Gender.female,
    labels: ["Warm", "Middle-Aged"],
    accent: "British",
  },
  {
    voice_id: "iP95p4xoKVk53GoZ742B",
    name: "Chris",
    speed: 0.75,
    tier: SubscriptionTierType.starter,
    price_multiplier: 1.0,
    languages: ["en", "es", "fr", "de", "zh", "ja", "ko", "pt", "hi", "ru"],
    gender: Gender.male,
    labels: ["Casual", "Middle-Aged"],
    accent: "American",
  },
  {
    voice_id: "g5CIjZEefAph4nQFvHAz",
    name: "Ethan",
    speed: 0.75,
    tier: SubscriptionTierType.pro,
    price_multiplier: 1.0,
    languages: ["en", "es", "fr", "de", "zh", "ja", "ko", "pt", "hi", "ru"],
    gender: Gender.male,
    labels: ["ASMR", "Soft", "Young"],
    accent: "American",
  },
  {
    voice_id: "bIHbv24MWmeRgasZH58o",
    name: "Will",
    speed: 0.8,
    tier: SubscriptionTierType.free,
    price_multiplier: 1.0,
    languages: ["en", "es", "fr", "de", "zh", "ja", "ko", "pt", "hi", "ru"],
    gender: Gender.male,
    labels: ["Friendly", "Young"],
    accent: "American",
  },
  {
    voice_id: "LcfcDJNUP1GQjkzn1xUU",
    name: "Nina",
    speed: 0.9,
    tier: SubscriptionTierType.free,
    price_multiplier: 1.0,
    languages: ["en", "es", "fr", "de", "zh", "ja", "ko", "pt", "hi", "ru"],
    gender: Gender.female,
    labels: ["Calm", "Young"],
    accent: "American",
  },
  {
    voice_id: "JBFqnCBsd6RMkjVDRZzb",
    name: "George",
    speed: 0.8,
    tier: SubscriptionTierType.starter,
    price_multiplier: 1.0,
    languages: ["en", "es", "fr", "de", "zh", "ja", "ko", "pt", "hi", "ru"],
    gender: Gender.male,
    labels: ["Warm", "Middle-Aged"],
    accent: "British",
  },
  {
    voice_id: "ErXwobaYiN019PkySvjV",
    name: "Antoni",
    speed: 0.8,
    tier: SubscriptionTierType.starter,
    price_multiplier: 1.0,
    languages: ["en", "es", "fr", "de", "zh", "ja", "ko", "pt", "hi", "ru"],
    gender: Gender.male,
    labels: ["Well-Rounded", "Young"],
    accent: "American",
  },
  {
    voice_id: "l32B8XDoylOsZKiSdfhE",
    name: "Carla",
    speed: 0.9,
    tier: SubscriptionTierType.starter,
    price_multiplier: 1.0,
    languages: ["en", "es", "fr", "de", "zh", "ja", "ko", "pt", "hi", "ru"],
    gender: Gender.female,
    labels: ["Meditative", "Young"],
  },
  {
    voice_id: "7Uw4vgM4Qb1qiwwUnu15",
    name: "Matteo", // Soothing Sam
    speed: 0.8,
    tier: SubscriptionTierType.starter,
    price_multiplier: 2.0,
    languages: ["en", "es", "fr", "de", "zh", "ja", "ko", "pt", "hi", "ru"],
    gender: Gender.male,
    labels: ["Middle-Aged", "Soothing"],
  },
  {
    voice_id: "AeRdCCKzvd23BpJoofzx",
    name: "Hugo", // Nathaniel C
    speed: 0.85,
    tier: SubscriptionTierType.free,
    price_multiplier: 1.0,
    languages: ["en", "es", "fr", "de", "zh", "ja", "ko", "pt", "hi", "ru"],
    gender: Gender.male,
    labels: ["Middle-Aged", "Soothing", "Calm"],
    accent: "British",
  },
  {
    voice_id: "bU2VfAdiOb2Gv2eZWlFq",
    name: "Roberto",
    speed: 0.8,
    tier: SubscriptionTierType.pro,
    price_multiplier: 2.0,
    languages: ["en", "es", "fr", "de", "zh", "ja", "ko", "pt", "hi", "ru"],
    gender: Gender.male,
    labels: ["Middle-Aged", "Sensual", "Warm"],
  },
  {
    voice_id: "51YRucvcq5ojp2byev44",
    name: "Lola", // Lovelace
    speed: 0.8,
    tier: SubscriptionTierType.starter,
    price_multiplier: 1.0,
    languages: ["en", "es", "fr", "de", "zh", "ja", "ko", "pt", "hi", "ru"],
    gender: Gender.female,
    labels: ["Soothing", "Intimate"],
    accent: "British",
  },
  {
    voice_id: "pSfivq1mIHnYTVwluxnz",
    name: "Quentin", // Carters Edge
    speed: 0.8,
    tier: SubscriptionTierType.pro,
    price_multiplier: 2.0,
    languages: ["en", "es", "fr", "de", "zh", "ja", "ko", "pt", "hi", "ru"],
    gender: Gender.male,
    labels: ["Rugged", "Sensual"],
  },
  {
    voice_id: "BgNdy2mYTwTmC5nWQ0rx",
    name: "Tobias", // Frederik
    speed: 0.8,
    tier: SubscriptionTierType.starter,
    price_multiplier: 2.0,
    languages: ["en", "es", "fr", "de", "zh", "ja", "ko", "pt", "hi", "ru"],
    gender: Gender.male,
    labels: ["Young", "Soft", "Calm"],
  },
  {
    voice_id: "gllMMawbYGTja23oQ3Vu",
    name: "Vivienne", // Crystal good
    speed: 0.95,
    tier: SubscriptionTierType.pro,
    price_multiplier: 2.0,
    languages: ["en", "es", "fr", "de", "zh", "ja", "ko", "pt", "hi", "ru"],
    gender: Gender.female,
    labels: ["Young", "Sensual"],
  },
  {
    voice_id: "uCAKWh24Y93ESUjKwRGP",
    name: "Matthew",
    speed: 0.9,
    tier: SubscriptionTierType.starter,
    price_multiplier: 2.0,
    languages: ["en", "es", "fr", "de", "zh", "ja", "ko", "pt", "hi", "ru"],
    gender: Gender.male,
    labels: ["Whispery", "ASMR"],
  },

  // French-only voices
  {
    voice_id: "TTtB1x9U8PF0Vgf20IAP",
    name: "Adrien",
    speed: 0.8,
    tier: SubscriptionTierType.free,
    price_multiplier: 1.0,
    languages: ["fr"],
    gender: Gender.male,
    labels: ["Middle-Aged", "Calm"],
  },
  {
    voice_id: "qMfbtjrTDTlGtBy52G6E",
    name: "Camille",
    speed: 0.8,
    tier: SubscriptionTierType.free,
    price_multiplier: 2.0,
    languages: ["fr"],
    gender: Gender.female,
    labels: ["Pleasant", "Calm"],
  },
  {
    voice_id: "RTFg9niKcgGLDwa3RFlz",
    name: "Théo",
    speed: 0.8,
    tier: SubscriptionTierType.free,
    price_multiplier: 1.0,
    languages: ["fr"],
    gender: Gender.male,
    labels: ["Middle-Aged", "Soothing"],
  },
  {
    voice_id: "EryqBbKuawX5rMsewc7f",
    name: "Jean-Luc",
    speed: 0.9,
    tier: SubscriptionTierType.starter,
    price_multiplier: 2.0,
    languages: ["fr"],
    gender: Gender.male,
    labels: ["Serene", "Middle-Aged"],
  },

  // German-only voices
  {
    voice_id: "Qi3EK8rWlKoVV4EG1MDJ",
    name: "Florian",
    speed: 0.8,
    tier: SubscriptionTierType.free,
    price_multiplier: 1.0,
    languages: ["de"],
    gender: Gender.male,
    labels: ["Young", "Neutral"],
  },
  {
    voice_id: "7eVMgwCnXydb3CikjV7a",
    name: "Lea",
    speed: 0.8,
    tier: SubscriptionTierType.free,
    price_multiplier: 1.0,
    languages: ["de"],
    gender: Gender.female,
    labels: ["Middle-Aged", "Attractive"],
  },

  // Spanish-only voices
  {
    voice_id: "D9MdulIxfrCUUJcGNQon",
    name: "Isabela",
    speed: 0.9,
    tier: SubscriptionTierType.starter,
    price_multiplier: 1.0,
    languages: ["es"],
    gender: Gender.female,
    labels: ["Calm", "Soft"],
  },
  {
    voice_id: "Nh2zY9kknu6z4pZy6FhD",
    name: "Antonio",
    speed: 0.8,
    tier: SubscriptionTierType.starter,
    price_multiplier: 1.0,
    languages: ["es"],
    gender: Gender.male,
    labels: ["Young", "Confident"],
  },
  {
    voice_id: "y6WtESLj18d0diFRruBs",
    name: "Pablo",
    speed: 0.8,
    tier: SubscriptionTierType.starter,
    price_multiplier: 1.0,
    languages: ["es"],
    gender: Gender.male,
    labels: ["Young", "Deep"],
  },

  // Portuguese-only voices
  {
    voice_id: "lWq4KDY8znfkV0DrK8Vb",
    name: "Yasmin",
    speed: 0.8,
    tier: SubscriptionTierType.free,
    price_multiplier: 1.0,
    languages: ["pt"],
    gender: Gender.female,
    labels: ["Soothing", "Carioca"],
  },
  {
    voice_id: "qarDw4DEvUqP3FBlpO0T",
    name: "Marcelo",
    speed: 0.8,
    tier: SubscriptionTierType.starter,
    price_multiplier: 1.0,
    languages: ["pt"],
    gender: Gender.male,
    labels: ["Young", "Calm"],
  },
  {
    voice_id: "oJebhZNaPllxk6W0LSBA",
    name: "Adriana",
    speed: 0.9,
    tier: SubscriptionTierType.free,
    price_multiplier: 1.0,
    languages: ["pt"],
    gender: Gender.female,
    labels: ["Middle-Aged", "Soothing"],
  },
  {
    voice_id: "uOjV7aFQoCQBSZxYyOds",
    name: "Joel",
    speed: 0.9,
    tier: SubscriptionTierType.starter,
    price_multiplier: 2.0,
    languages: ["pt"],
    gender: Gender.male,
    labels: ["Middle-Aged", "Poetic"],
  },
  {
    voice_id: "7eUAxNOneHxqfyRS77mW",
    name: "Beatriz",
    speed: 0.8,
    tier: SubscriptionTierType.pro,
    price_multiplier: 2.0,
    languages: ["pt"],
    gender: Gender.female,
    labels: ["Middle-Aged", "Warm"],
  },

  // Hindi-only voices
  {
    voice_id: "50YSQEDPA2vlOxhCseP4",
    name: "Saanu",
    speed: 0.8,
    tier: SubscriptionTierType.free,
    price_multiplier: 1.0,
    languages: ["hi"],
    gender: Gender.female,
    labels: ["Middle-Aged", "Soothing"],
  },
  {
    voice_id: "XcWoPxj7pwnIgM3dQnWv",
    name: "Shivi",
    speed: 0.9,
    tier: SubscriptionTierType.starter,
    price_multiplier: 1.0,
    languages: ["hi"],
    gender: Gender.female,
    labels: ["Young", "Calm"],
  },
  {
    voice_id: "F4AXgTwG8nWPB9dcXaTh",
    name: "Krishna",
    speed: 0.8,
    tier: SubscriptionTierType.free,
    price_multiplier: 1.0,
    languages: ["hi"],
    gender: Gender.male,
    labels: ["Middle-Aged", "Spiritual"],
  },
  {
    voice_id: "MF4J4IDTRo0AxOO4dpFR",
    name: "Devi",
    speed: 0.75,
    tier: SubscriptionTierType.starter,
    price_multiplier: 1.0,
    languages: ["hi"],
    gender: Gender.female,
    labels: ["Young", "Rajasthan"],
  },
  {
    voice_id: "mg9npuuaf8WJphS6E0Rt",
    name: "Aisha",
    speed: 0.8,
    tier: SubscriptionTierType.pro,
    price_multiplier: 1.0,
    languages: ["hi"],
    gender: Gender.female,
    labels: ["Young", "Intimate"],
  },
  {
    voice_id: "BpjGufoPiobT79j2vtj4",
    name: "Avni",
    speed: 0.75,
    tier: SubscriptionTierType.free,
    price_multiplier: 1.0,
    languages: ["hi"],
    gender: Gender.female,
    labels: ["Young", "Calm"],
  },

  // Korean-only voices
  {
    voice_id: "nbrxrAz3eYm9NgojrmFK",
    name: "Min-Joon",
    speed: 0.8,
    tier: SubscriptionTierType.free,
    price_multiplier: 1.0,
    languages: ["ko"],
    gender: Gender.male,
    labels: ["Young", "Neutral"],
  },
  {
    voice_id: "DMkRitQrfpiddSQT5adl",
    name: "Jjeong",
    speed: 0.8,
    tier: SubscriptionTierType.starter,
    price_multiplier: 1.0,
    languages: ["ko"],
    gender: Gender.female,
    labels: ["Middle-Aged", "Seoul"],
  },
  {
    voice_id: "z6Kj0hecH20CdetSElRT",
    name: "Yuna",
    speed: 0.8,
    tier: SubscriptionTierType.free,
    price_multiplier: 1.0,
    languages: ["ko"],
    gender: Gender.female,
    labels: ["Young", "Soothing"],
  },

  // Chinese-only voices
  {
    voice_id: "hkfHEbBvdQFNX4uWHqRF",
    name: "Xiao Yu",
    speed: 0.8,
    tier: SubscriptionTierType.free,
    price_multiplier: 1.0,
    languages: ["zh"],
    gender: Gender.female,
    labels: ["Young", "Pleasant"],
  },
  {
    voice_id: "WuLq5z7nEcrhppO0ZQJw",
    name: "Tian Yu",
    speed: 0.8,
    tier: SubscriptionTierType.free,
    price_multiplier: 1.0,
    languages: ["zh"],
    gender: Gender.male,
    labels: ["Middle-Aged", "Deep"],
  },
  {
    voice_id: "FjfxJryh105iTLL4ktHB",
    name: "Liang",
    speed: 0.8,
    tier: SubscriptionTierType.starter,
    price_multiplier: 2.0,
    languages: ["zh"],
    gender: Gender.female,
    labels: ["Young", "Soothing"],
  },
];
// Assign sortOrder based on array position
voices.forEach((v, i) => {
  v.sortOrder = i;
});

async function main() {
  console.log('Seeding voices...');

  // 1) Upsert all voices
  for (const voice of voices) {
    await prisma.voice.upsert({
      where: { voice_id: voice.voice_id },
      update: {
        name: voice.name,
        speed: voice.speed,
        tier: voice.tier,
        price_multiplier: voice.price_multiplier,
        languages: voice.languages,
        gender: voice.gender,
        labels: voice.labels,
        ...(voice.accent ? { accent: voice.accent } : {}),
        sortOrder: voice.sortOrder!,
      },
      create: {
        voice_id: voice.voice_id,
        name: voice.name,
        speed: voice.speed,
        tier: voice.tier,
        price_multiplier: voice.price_multiplier,
        languages: voice.languages,
        gender: voice.gender,
        labels: voice.labels,
        accent: voice.accent ?? null,
        sortOrder: voice.sortOrder!,
      },
    });
    console.log(`Upserted voice: ${voice.name}`);
  }

  // 2) Remove any voices no longer present in the seed array
  const seedIds = voices.map((v) => v.voice_id);
  const { count } = await prisma.voice.deleteMany({
    where: { voice_id: { notIn: seedIds } },
  });
  console.log(`Removed ${count} voices no longer in seed file`);

  console.log('Voices seeding finished.');
}


main()
  .catch((e) => {
    console.error('Error during seeding', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
